MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"

#  WEIGHT: "/home/zoey/nas/zoey/github/maskrcnn-benchmark/checkpoints/finetune/model_0000000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STEM_IN_CHANNELS: 3
#    STEM_DIN_CHANNELS: 1
    STEM_RGBDIN_CHANNELS: 6
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11

  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False

  ROI_POSE_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
    NUM_CLASSES: 11
    NUM_POSE_BINS: 6

  # Main branches
  RGB_ON: False
  COARSE_ON: False
  BBOXFeature_ON: False
  #Main heads
  POSE_ON: True
  MASK_ON: True
  #Pose regression or classification
  REGRESSION_ON: False
  # Use for Ablation study: depth stream.
  DEPTH_ON: True
  DCOARSE_ON: True
  DBBOXFeature_ON: True

DATASETS:
  TRAIN: ('kitchen1_val8',)
  TEST: ('kitchen1_val8',)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (0, 15000, 20000)
  MAX_ITER: 25000
OUTPUT_DIR: "/home/zoey/nas/zoey/github/maskrcnn-benchmark/checkpoints/data1_depth"
